#ifndef CONSTANTS_HPP
#define CONSTANTS_HPP
#pragma once

#define GRAVITY 9.8f

#define MINIMUM_WINDOW_WIDTH 480
#define MINIMUM_WINDOW_HEIGHT 300
#define INITIAL_WINDOW_WIDTH 800
#define INITIAL_WINDOW_HEIGHT 500

#define BULLET_MAX_LIFETIME 1000

#endif